baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'doityourblog'
theme = 'roadster'
sectionPagesMenu = 'main'

[Author]
  name = "rick"
  bio = "hey tutek?"

[Params]
  toc = true
  pager = true

[Params.sidebar]
  home = "right"
  list = "right"
  widgets = ["search", "recent", "categories", "social"]

[Params.style.vars]
  highlightColor = "#efcc00"

[Params.widgets.social]
  cached = true
  github = "r1ckhdk"
  mastodon = "@malukopower"
  email = "rick@riseup.net"
