baseURL = 'https://doityourblog.org/'
languageCode = 'pt-br'
title = 'doityourblog'
theme = 'roadster'
sectionPagesMenu = 'main'

[Author]
  name = "rick"
  bio = "hey tutek?"

[Params]
  toc = true
  pager = true
  googleFontsLink = "https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"

[Params.sidebar]
  home = "right"
  list = "right"
  widgets = ["search", "recent", "categories", "social"]

[Params.style.vars]
  fontFamilyPrimary = "JetBrains Mono"
  highlightColor = "#efcc00"

[Params.widgets.social]
  cached = true
  github = "r1ckhdk"
  mastodon = "@malukopower"
  email = "rick@riseup.net"
