baseURL = 'https://doityourblog.org/'
languageCode = 'pt-br'
title = 'DOITYOURBLOG'
theme = 'roadster'

[Params]
  pager = true
  readmore = true
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
  post_meta = ["author", "date", "categories"]
  authorbox = true
  customCSS = ["css/custom.css"]

[Params.sidebar]
  home = "right"
  single = "right"
  list = "right"
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.thumbnail]
  visibility = ["list"]

[Params.style.vars]
  fontFamilyPrimary = "Fira Sans"
  highlightColor = "#ffc40c"

[Params.widgets.social]
  cached = true
  github = "r1ckhdk"
  mastodon = "@malukopower"
  email = "rick@riseup.net"


# lets me user raw html in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Sobre'
    pageRef = '/about'
    weight = 15

  [[menus.main]]
    name = 'RSS'
    url = '/index.xml'
    weight = 20
